<a href="https://colab.research.google.com/github/QuaternionPaul/my-first-repo/blob/main/1_D_Ising_Model_Simulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Simulation of the 1-D Ising Model

The code for this simulation of the 1-D Ising Model/Ising Chain was adapted from [here](https://hockygroup.hosting.nyu.edu/exercise/ising-1d.html).

The goal of this investigation was to demonstrate that the computationally expensive MCMC step (for the Metropolis-Hastings algorithm) could be simply replaced by a probabilistic programming language (PPL) with similar results. Otherwise we use the same visualization backend and framework to display and compare the results.

In the first half of this notebook, we

In the second half, we build upon this framework by reimplementing the entire 1-D Ising Chain model with MCMC step in a PPL, namely PyMC3. We show that we can get similar results with much impler and fewer lines of code in the PPL, demonstrating the potential of PPLs to speedup workflows when modeling probabilistic pehnomena.

In [69]:
#setup the notebook
%pylab inline
import numpy as np


Populating the interactive namespace from numpy and matplotlib
time: 7.18 ms (started: 2023-06-16 08:11:46 +00:00)


/usr/local/lib/python3.10/dist-packages/IPython/core/magics/pylab.py:159: UserWarning: pylab import has clobbered these variables: ['step', 'trace']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


For a sim

In [70]:
def energy_ising_1d(configuration,J,h):
    num_spins = len(configuration)
    energy = 0.0
    for i in range(num_spins):
        spini = configuration[i]
        #set the value of spin i+1, make sure to test if i+1<num_spins, and otherwise account for periodic boundaries
        #you can do this with an if statement if you have to
        ip1 = (i+1)%num_spins
        spinip1 = configuration[ip1]

        energy = energy - J * (spini * spinip1) - h*spini

    return energy

#Check that the energy is correct
test_num_spins = 10
#this should be true for any J, h
test_J = 1
test_h = 2

test_configuration_1 = -1*np.ones(test_num_spins)
test_configuration_2 = +1*np.ones(test_num_spins)

test_configuration_3 = +1*np.ones(test_num_spins)
#this sets even entries to -1
test_configuration_3[::2] = -1

print("Test Config 1:", test_configuration_1)
print("Energy Config 1:", energy_ising_1d(test_configuration_1,test_J,test_h))
print("Expected Energy Config 1:",test_num_spins*(test_h-test_J))
print()
print("Test Config 2:", test_configuration_2)
print("Energy Config 2:", energy_ising_1d(test_configuration_2,test_J,test_h))
print("Expected Energy Config 2:",-test_num_spins*(test_h+test_J))
print()
print("Test Config 3:", test_configuration_3)
print("Energy Config 3:", energy_ising_1d(test_configuration_3,test_J,test_h))
print("Expected Energy Config 3:",test_num_spins*test_J)

Test Config 1: [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
Energy Config 1: 10.0
Expected Energy Config 1: 10

Test Config 2: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Energy Config 2: -30.0
Expected Energy Config 2: -30

Test Config 3: [-1.  1. -1.  1. -1.  1. -1.  1. -1.  1.]
Energy Config 3: 10.0
Expected Energy Config 3: 10
time: 1.99 ms (started: 2023-06-16 08:11:47 +00:00)


# Section 1
## Monte Carlo Simulation using Metropolis-Hastings algorithm (Non-PPL)

First we analyse the 1-D Ising chain using Monte Carlo simulation, but not using a PPL. The Metropolis-Hastings algorithm is performed in selecting whether or not to flip individual spin-flips.

In [71]:


#set a seed for the random number generator here. For a given seed, all of your results should be identical
random_seed = 1
np.random.seed(random_seed)

def energy_difference(J, h, si, sleft, sright):
    #fill in the formula for the energy difference from flipping spin i,
    #which has value si= 1 or -1, with spin values sleft and sright on the left and right
    dE = 2*h*si + 2*J*si*(sleft+sright)
    return dE

def metropolis_mc_fast(n_steps, n_lattice_sites, beta, J, h, debug=False,save_freq=10):
    # we can start with a random configuration of size n_lattice_sites by generating a random list
    #    of zeros and twos, then subtracting 1, the following does that, do you see why? Play around
    #   with this function in an empty box if you don't
    configuration = 2*np.random.randint(2, size=n_lattice_sites) - 1
    average_spins = []

    if debug is True:
        print("Starting configuration:",configuration)

    current_energy = energy_ising_1d(configuration,J,h)
    for i in range(n_steps):

        #set this like you did above:
        spin_to_change = np.random.randint(n_lattice_sites)

        si = configuration[spin_to_change]
        #now figure out the values of the spin to the left and the spin to the right, remembering
        #  to take into account periodic boundary conditions for both
        # you can use if statements if you have to
        sright = configuration[(spin_to_change+1)%n_lattice_sites]
        sleft = configuration[(spin_to_change-1)%n_lattice_sites]

        dE = energy_difference(J,h,si,sleft,sright)

        r = np.random.random()
        # fill in the metropolis critereon, using dE
        if r<min(1,np.exp(-beta*(dE))) :
            #flip the spin
            configuration[spin_to_change]*=-1
            # update the energy
            current_energy += dE
        else:
            pass

        #this computes the average spin
        average_spin = configuration.mean()

        if i%save_freq == 0:
            average_spins.append(average_spin)

        if debug and i%10==0:
            print("%i: "%i,configuration,"Energy:",current_energy,"Spin:",average_spin)

    return average_spins

#do a test high temperature simulation
print("High temperature:")
average_spins = metropolis_mc_fast(n_steps=100, n_lattice_sites=10, beta=0.1, J=1, h=2, debug=True)
#do a test on a low temperature simulation
print("Low temperature:")
average_spins = metropolis_mc_fast(n_steps=100, n_lattice_sites=10, beta=1, J=1, h=2, debug=True)



High temperature:
Starting configuration: [ 1  1 -1 -1  1  1  1  1  1 -1]
0:  [-1  1 -1 -1  1  1  1  1  1 -1] Energy: -6.0 Spin: 0.2
10:  [-1  1  1 -1 -1  1  1  1  1  1] Energy: -10.0 Spin: 0.4
20:  [ 1 -1  1  1  1 -1  1 -1  1  1] Energy: -6.0 Spin: 0.4
30:  [ 1 -1 -1  1  1  1 -1 -1  1  1] Energy: -6.0 Spin: 0.2
40:  [-1 -1 -1 -1  1  1  1 -1 -1  1] Energy: 2.0 Spin: -0.2
50:  [-1  1 -1  1 -1  1 -1 -1 -1 -1] Energy: 10.0 Spin: -0.4
60:  [-1  1  1  1  1  1  1  1  1 -1] Energy: -18.0 Spin: 0.6
70:  [-1 -1 -1 -1 -1 -1  1 -1  1 -1] Energy: 10.0 Spin: -0.6
80:  [ 1  1  1  1 -1 -1  1  1 -1 -1] Energy: -6.0 Spin: 0.2
90:  [-1  1  1 -1  1 -1 -1  1  1 -1] Energy: 2.0 Spin: 0.0
Low temperature:
Starting configuration: [-1 -1  1 -1 -1 -1  1 -1  1  1]
0:  [ 1 -1  1 -1 -1 -1  1 -1  1  1] Energy: 2.0 Spin: 0.0
10:  [ 1 -1  1  1  1  1  1  1  1  1] Energy: -22.0 Spin: 0.8
20:  [1 1 1 1 1 1 1 1 1 1] Energy: -30.0 Spin: 1.0
30:  [1 1 1 1 1 1 1 1 1 1] Energy: -30.0 Spin: 1.0
40:  [1 1 1 1 1 1 1 1 1 1] Ene

**Remarks:**

N.B: The above code was taken and adapted from [here](https://hockygroup.hosting.nyu.edu/exercise/ising-1d.html), solely for comparision purposes to show how the Metropolis-Hastings algorithm can be implemented manually without the use of a PPL, and what a 1-D Ising chain should behave like. In the following segments, we build upon this framework to replicate this basic simulation of a 1-D Ising chain, albeit in a novel implementation using a PPL.

It is clear that the non-probabilistic code is highly non-optimised with multiple nested for-loops, and probably would scale poorly in terms of computation as the length of the 1-D Ising chain (n_lattice_site) and number of simulated steps (n_steps) are increased.



#Section 2

#Simulation of 1-D Ising Chain using a PPL (PyMC3)

The following code adapts ideas from [here](https://tanyaschlusser.github.io/posts/mcmc-and-the-ising-model/), where a visualisation of the phase transition in the 2-D Ising model using the PyMC3 PPL is shown.

However we build upon this to make several novel technical contributions:

(1) extending the original 2-D framework to demonstrate how PyMC3 can be applied in the novel context of a 1-D Ising Chain.

(2) extending the total Hamiltonian to also consider the energy from interaction with a non-zero external magnetic field $h$

In this regard, the original code simplified the Hamiltonian by ignoring $\mathscr{H}^{1}_{Ext}$. We modify the function to be able to calculate the energy changes by including this new term in the total 1-D Hamiltonian:

\begin{equation}
    \mathscr{H}_{1D} = \mathscr{H}^{1}_{NN} + \mathscr{H}^{1}_{Ext} = \sum \limits^{N-1} \limits_{i=0} - J\sigma_{i}\cdot\sigma_{i+1} - h\cdot\sigma_{i}
\end{equation}

(3) refactor the implementation to use supported versions of the PyTensor and PyMC3 libraries. The original code used the Theano library, which has been discontinued in 2020 and had issues with being installed due to source errors.

We show that our implementation (in a PPL) is much shorter and simpler (in terms of lines of code) than the equivalent non-probabilistic code, with vectorized functions provided under the PyMC3 library removing the need for multiple-nesting of for loops as in the non-probabilistic implementation. The PyMC3 implementation also demonstrates expected features and behaviour for a 1-D Ising Chain, in good agreement with the non-probabilistic implementation above.

In [3]:
from functools import partial

import pymc as pm
import numpy as np
import pytensor.tensor as pt

In [4]:
def convert_spins (spins):

  # Bernoulli distributions outputs array of 1s and 0s
  # This fn converts original spins-array of 1s and 0s -> 1s and -1s
  # +1 represents spin-up, -1 represents spin-down

  proper = 2*spins - 1

  return proper


def get_H_NN(spins, J=1):

  # Calculate nearest-neighbour interaction Hamiltonian, H_NN

  spins_p = convert_spins(spins)

  H_NN = - J*(
  pt.roll(spins_p, 1, axis=0) * spins +
  pt.roll(spins_p, -1, axis=0) * spins
  )
  return H_NN

def get_H_Ext(spins, h=1):

  # Calculate external magnetic field interaction Hamiltonian, H_Ext

  H_ext = -h*spins

  return H_ext

def get_boltz_weight(spins, T=1):

  spins_p = convert_spins(spins)

  H_total = get_H_NN(spins) + get_H_Ext(spins)

  # WLOG, assume Boltzmann constant k_B = 1
  boltzmann_weight = pm.math.exp(-H_total/T)

  return boltzmann_weight


PyMC3 is a Python-based package that is focused on probabilistic machine learning and Bayesian modeling.

PyMC3 allows users access to a rich library of vectorized functions and statistical packages, that makes statistical inference tasks much more straight-forward and faster as compared to manual implementation. PyMC3 offers good support and access to powerful MCMC algorithms (Metropolis-Hastings, Sequential Monte Carlo, Hamiltonian Monte Carlo etc) and variational inference methods.

This opens up exciting possibilities for users to gain access to powerful new statistical methods such as No U-Turn Sampling (NUTS) with just a single function call from PyMC3, greatly speeding up programming workflows.

In the following, we demonstrate how the Metropolis-Hastings algorithm for Monte Carlo simulation of the 1-D Ising chain can just be built in a simple PyMC3.Model() class, with just a few lines of code.

In [13]:
basic_model = pm.Model()


with basic_model as model:
  T=100 # Temperature T will be defined as an argument in wrapper function.

  # Use the Bernoulli Distribution. Outputs an array of random 1,0s of shape/length 10
  y = pm.Bernoulli('y', 0.5, shape=10)

  # pm.Potential is summed and added to the overall log-likelihood.
  # This conditions the MCMC chain on the given argument function, which is the Boltzmann weighting
  boltz_weight = pm.Potential('b', -(get_H_NN(convert_spins(y)) + get_H_Ext(convert_spins(y)))/T )

  # 'scaling'
  scaling = 0.08

  # PyMC3 allows us to conveniently choose the MCMC sampler method by calling the  supported function.
  # Other supported MCMC methods include Sequential MC, Hamiltonian MC, NUTS
  step = pm.BinaryMetropolis([y], scaling=scaling)

  # Run the sample, store all outputs in trace
  trace = pm.sample(5000, step=step, return_inferencedata=False)

We embed this PyMC3 model within a wrapper function **ppl_approach()**, that allows us to conveniently invoke and perform inference on (n_steps) number of MCMC steps, on 1-D Ising chains of arbitrary length (n_lattice_sites).

---



In [8]:
def ppl_approach(n_steps, n_lattice_sites, T, J=1, h=0, save_freq=10):

  basic_model = pm.Model()

  with basic_model as model:
    y = pm.Bernoulli('y', 0.5, shape=n_lattice_sites)

    boltz_weight = pm.Potential('b', -(get_H_NN(convert_spins(y)) + get_H_Ext(convert_spins(y)))/T )

    scaling = 0.008

    step = pm.BinaryMetropolis([y], scaling=scaling)

    trace = pm.sample(n_steps, step=step, return_inferencedata=False)

  output = 2*trace["y"][::save_freq*2]-1
  print(output)


We call the function to take n_steps = 5000 iterations of the MCMC algorithm, to quickly generate 5000 instances of 10-site 1-D Ising chains.

By default, PyMC3 samples two independent MCMC chains, in order to ensure convergence. One can change the number of chains by passing the "sample =" argument in the **sample()** function.

(The API note for the sample function is from: https://www.pymc.io/projects/docs/en/stable/api/generated/pymc.sample.html)

In [9]:
print("Low Temperature: ")

ppl_approach( 5000, 10, T=1, J=1, h=1, save_freq = 500)

Low Temperature: 


[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [10]:
print("High Temperature: ")

ppl_approach( 5000, 10, T=10, J=1, h=1, save_freq = 500)


High Temperature: 


[[-1 -1 -1  1  1  1 -1  1  1 -1]
 [ 1 -1 -1 -1 -1 -1 -1 -1  1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1 -1  1  1  1  1  1  1  1]
 [ 1  1  1  1 -1 -1 -1  1 -1 -1]
 [-1 -1  1  1 -1  1 -1 -1 -1 -1]
 [-1 -1  1  1  1  1 -1 -1 -1 -1]
 [-1 -1  1 -1 -1  1 -1 -1 -1  1]
 [-1  1 -1 -1 -1 -1 -1 -1  1  1]]


**Remarks:**

Our PyMC3 implementation of Monte-Carlo simulation of the 1-D Ising Chain agrees well with theory and the previous non-probabilistic implementation.

Our implementation is also more general, as we consider the extra added term of the Hamiltonian of the interaction of individual spins with an external magnetic field $h=1$, $\mathscr{H}^{1}_{Ext} = \sum \limits^{N-1} \limits_{i=0} - h\cdot\sigma_{i}$, which was absent in the non-PPL implementation in Section 1.

For an arbitrary **Low Temperature** (T=1), we see that all the spin-values = +1, denoting that all the spins are aligned.

For an arbitrary **High Temperature** (T=10), we see that the spin-values are largely random and highly-disordered, switching randomly between -1 and +1.

This behaviour is expected and agrees well with theory. At low temperatures, the spins will largely be aligned with the external magnetic field $h$ with spin = +1, as random thermal excitations are too weak and have low probabiility of flipping the spin during the MCMC chain. At high temperatures the stronger thermal fluctuations/excitations lead to high probability of flipping of the spin-flips during the MCMC chain. Hence the spin-flips will be largely disordered and random at the end.

PyMC3 supports an extensive list of MCMC based samplers: https://www.pymc.io/projects/docs/en/stable/api/samplers.html

The user can just change the sampling algorithm in ppl_approach() by swapping the smapling function, without having to rewrite the entire MCMC function froms scrath.

#Section 3

#Speedup of PPL versus Non-PPL Implementations

In [64]:
!pip install ipython-autotime
%load_ext autotime

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 21.0 MB/s eta 0:00:00
time: 239 µs (started: 2023-06-16 08:09:27 +00:00)


Now let's compare the running time for the two functions: **standard_approach** and **ppl_approach**.

In [74]:
ppl_approach(5000, 200, T=1, J=1, h=0, save_freq = 500 )

time: 3.06 s (started: 2023-06-16 08:12:55 +00:00)


In [75]:
metropolis_mc_fast(n_steps=5000, n_lattice_sites=200, beta=1, J=1, h=20, debug=True)

Starting configuration: [-1 -1 -1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1 -1
  1 -1  1 -1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1
 -1  1 -1  1 -1  1  1 -1 -1  1  1  1  1 -1 -1  1  1  1 -1 -1  1 -1  1  1
 -1  1  1  1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1  1  1  1 -1 -1
 -1  1 -1  1 -1  1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1  1  1  1  1
  1  1 -1  1  1 -1 -1  1 -1 -1 -1 -1 -1 -1 -1 -1  1  1 -1  1  1 -1 -1  1
  1  1  1 -1 -1  1  1  1 -1 -1  1  1  1  1  1  1  1 -1  1 -1  1 -1  1 -1
  1  1  1 -1  1  1  1  1  1 -1  1  1  1  1 -1  1  1  1 -1  1  1  1  1 -1
  1 -1  1  1 -1  1  1 -1]
0:  [-1 -1 -1 -1  1 -1  1 -1  1 -1 -1  1 -1  1 -1  1 -1  1 -1 -1 -1  1 -1 -1
  1 -1  1 -1  1 -1  1  1 -1 -1 -1 -1  1 -1 -1 -1 -1 -1  1 -1  1 -1 -1  1
 -1  1 -1  1 -1  1  1 -1 -1  1  1  1  1 -1 -1  1  1  1 -1 -1  1 -1  1  1
 -1  1  1  1  1  1  1 -1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1  1  1  1 -1 -1
 -1  1 -1  1  1  1 -1 -1  1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1  1  1  1 

[0.07,
 0.1,
 0.17,
 0.19,
 0.26,
 0.29,
 0.34,
 0.38,
 0.41,
 0.44,
 0.49,
 0.52,
 0.55,
 0.57,
 0.61,
 0.65,
 0.66,
 0.68,
 0.68,
 0.68,
 0.72,
 0.74,
 0.75,
 0.76,
 0.77,
 0.81,
 0.84,
 0.84,
 0.84,
 0.84,
 0.84,
 0.84,
 0.85,
 0.86,
 0.86,
 0.89,
 0.89,
 0.9,
 0.9,
 0.9,
 0.91,
 0.92,
 0.93,
 0.94,
 0.94,
 0.95,
 0.95,
 0.95,
 0.95,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.96,
 0.97,
 0.97,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 0.99,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 

time: 1.18 s (started: 2023-06-16 08:12:59 +00:00)


In [ ]:

basic_model_3 = pm.Model()

with basic_model_3 as model:
  T=0.001
  #Outputs a Theano TensorVariable!!!!
  k = pm.Bernoulli('k', 0.5, shape=10)


  # Potential adds to the model's log-probability

  #boltz_weight = pm.Potential('b', pm.math.log(get_boltz_weight(y)))

  boltz_weight = pm.Potential('b', (get_H_Ext(convert_spins(k)) + get_H_NN(convert_spins(k)))/T)

  scaling = 0.0005

  step = pm.BinaryMetropolis([k], scaling=scaling)

  trace = pm.sample(1000, step=step, return_inferencedata=False)

/usr/local/lib/python3.10/dist-packages/pymc/step_methods/metropolis.py:408: RuntimeWarning: overflow encountered in exp
  "accept": np.exp(accept),


#References

[1]

[2]

[3]